language: node_js
node_js:
- '8'
env:
  global:
    secure: JXrw1lwn6g6AQ50l5UOhKOZR4KSWu0iKPmgFsq4Hx+QPEc+wyNVrH4l7MMBA1JldC3emJYNcsrd/Tjsxpm4dJM/XUY/lLFy8bSMPE9BJIUMm8//zMs20k30Bwd/30K5LVwiUIVc+PimsWpKDPsBYH5fNeHBOKPyzifvxlQBXxverMpxSKN7qX/ZpCa/eU6uJ8xCYTOmIyUBuoG1Fl30nXOxMvdA9RViHDTs7MbpP6v4R6UwXMd0rqC8auck7P4kFTsn/prZ//BlLpR7ODj2qKSClNPiXzROv8HzlvepMvedlXDoL7HGCzVCm2wbfMorzD9A4jEeOKB7CXy61RypJ9zVD7WzHsGW4TK18/NfLUf9AjvzViomqPXKZdbJO05OP8yPLt5OuRcObiQaMJM1r0Gr5lOerpNzD6/z1gR41fEyj+KeJb8DA/M85E3UrjixbZXqwfMfznBNziBN3UQrZmZMPyGUzF9AIFPCe9TmEBhPm5NnA6nLeccSwOHjQLAk3dz+Ipre0/vPU/P3LAeFUqehmeSQP08BOX5C/d14jzkHB5MEuavrHBaD930VtDFeqyPJDgLFOW4c60XH3bQ928DSwExULdJpZpiyTRIKVqUKfyGm4bdz0YYW++rdBs31WyYcO0u925V2xn5bOeXAtT+gn+l3cpF7wJInRV4mpTFk=
dist: trusty
sudo: false
addons:
  chrome: stable
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
after_success:
- bash travis/commit.sh
deploy:
  provider: npm
  email: nooooru@gmail.com
  api_key:
    secure: V0xTQdyFmvvYWR0Amo0WLuICKApeyHaVEn52hErO/6chwBa6s7VsQbVcTBOVZKUDgHh1PmlZeeSMYAK5/QOf0xABmdqhUQKls+XEX+nYSrVr/pF7byqXLfmKGfeCTyyqSDVsRaYX6Dww3FcZKMOPKK4sRqW8JlI881XhRVmbZZUxF3o5YJTmIS2y4CwgP4qWkSzkm945Bn1OTbIn2Iv1pBWDPN+pCy+sssbCda9k9M+YPRRfY51qny1Sc9ENn2f0RdoqottFmz75pB3RWSXnNMuzvWVt6LGAVHwSn9zUyrwB3K0UV3JCghhZAKP7IYG9yunWXeM8kam3EoqpweA2eNakbrZ7R2+1jLVY2t2HQdFXcWZc44a5mcvP2KfwrJVi5sZlLlIymOKW5jvyjRFuLVNHT3r+aiCR/w9CAUaWZ5fsDtNzpNbbCeGIzJm2NUYdYl+UOwijcYjllE4LZUFUDSRL1qJVUG/S9OIdBc0aiDeOq/hWQfPi0RacKAqdcAhyP+/OaZdFOGcjyFhGYWMnIUsr6gyBPZbKBQjzmK2lEuinPlBm9X7vXhipHs7CfiXaRAFstg06IkH/ICPT5QBAnBilvjviOvlpbUrjXYTmbsjeY9kdNPo+afemNmEruXiw35gxwuN7UNyegCc5UGB9xMBNW2U/2ZxcDKN8w4R9zx4=
  on:
    repo: noru/utils
